# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClientView.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClientView(object):
    def __init__(self, dbClientManage, windowClientView):
        self.dbClientView = dbClientManage # copy database to a local variable. 
        self.windowClientView = windowClientView #copy window var to a loca var.

    def setup(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(491, 304)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LabelName = QtWidgets.QLabel(self.centralwidget)
        self.LabelName.setGeometry(QtCore.QRect(20, 30, 61, 21))
        self.LabelName.setObjectName("LabelName")
        self.LabelSurname1 = QtWidgets.QLabel(self.centralwidget)
        self.LabelSurname1.setGeometry(QtCore.QRect(20, 60, 61, 21))
        self.LabelSurname1.setObjectName("LabelSurname1")
        self.LabelSurname2 = QtWidgets.QLabel(self.centralwidget)
        self.LabelSurname2.setGeometry(QtCore.QRect(20, 90, 61, 21))
        self.LabelSurname2.setObjectName("LabelSurname2")
        self.LabelDNI = QtWidgets.QLabel(self.centralwidget)
        self.LabelDNI.setGeometry(QtCore.QRect(20, 120, 61, 21))
        self.LabelDNI.setObjectName("LabelDNI")
        self.LabelPhone = QtWidgets.QLabel(self.centralwidget)
        self.LabelPhone.setGeometry(QtCore.QRect(20, 150, 61, 21))
        self.LabelPhone.setObjectName("LabelPhone")
        self.labelNameView = QtWidgets.QLabel(self.centralwidget)
        self.labelNameView.setGeometry(QtCore.QRect(110, 30, 201, 21))
        self.labelNameView.setObjectName("labelNameView")
        self.labelSurname1View = QtWidgets.QLabel(self.centralwidget)
        self.labelSurname1View.setGeometry(QtCore.QRect(110, 60, 201, 21))
        self.labelSurname1View.setObjectName("labelSurname1View")
        self.labelSurname2View = QtWidgets.QLabel(self.centralwidget)
        self.labelSurname2View.setGeometry(QtCore.QRect(110, 90, 201, 21))
        self.labelSurname2View.setObjectName("labelSurname2View")
        self.labelDNIView = QtWidgets.QLabel(self.centralwidget)
        self.labelDNIView.setGeometry(QtCore.QRect(110, 120, 201, 21))
        self.labelDNIView.setObjectName("labelDNIView")
        self.labelPhoneView = QtWidgets.QLabel(self.centralwidget)
        self.labelPhoneView.setGeometry(QtCore.QRect(110, 150, 201, 21))
        self.labelPhoneView.setObjectName("labelPhoneView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LabelName.setText(_translate("MainWindow", "Nombre:"))
        self.LabelSurname1.setText(_translate("MainWindow", "Apellido 1:"))
        self.LabelSurname2.setText(_translate("MainWindow", "Apellido 2:"))
        self.LabelDNI.setText(_translate("MainWindow", "DNI:"))
        self.LabelPhone.setText(_translate("MainWindow", "Teléfono:"))
        self.labelNameView.setText(_translate("MainWindow", "NameView"))
        self.labelSurname1View.setText(_translate("MainWindow", "Surname1View"))
        self.labelSurname2View.setText(_translate("MainWindow", "Surname2View"))
        self.labelDNIView.setText(_translate("MainWindow", "DNIView"))
        self.labelPhoneView.setText(_translate("MainWindow", "PhoneView"))