# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClientView.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClientView(object):
    def __init__(self, clientSel, dbClientManage, windowClientView):
        self.dbClientView = dbClientManage # copy database to a local variable. 
        self.windowClientView = windowClientView #copy window var to a loca var.
        self.clientData = clientSel


    def setup(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 750)
        MainWindow.setMaximumSize(QtCore.QSize(450, 750))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LabelName = QtWidgets.QLabel(self.centralwidget)
        self.LabelName.setGeometry(QtCore.QRect(20, 30, 61, 21))
        self.LabelName.setObjectName("LabelName")
        self.LabelSurname1 = QtWidgets.QLabel(self.centralwidget)
        self.LabelSurname1.setGeometry(QtCore.QRect(20, 60, 61, 21))
        self.LabelSurname1.setObjectName("LabelSurname1")
        self.LabelSurname2 = QtWidgets.QLabel(self.centralwidget)
        self.LabelSurname2.setGeometry(QtCore.QRect(20, 90, 61, 21))
        self.LabelSurname2.setObjectName("LabelSurname2")
        self.LabelDNI = QtWidgets.QLabel(self.centralwidget)
        self.LabelDNI.setGeometry(QtCore.QRect(20, 120, 61, 21))
        self.LabelDNI.setObjectName("LabelDNI")
        self.LabelPhone = QtWidgets.QLabel(self.centralwidget)
        self.LabelPhone.setGeometry(QtCore.QRect(20, 150, 61, 21))
        self.LabelPhone.setObjectName("LabelPhone")
        self.lineNameView = QtWidgets.QLineEdit(self.centralwidget)
        self.lineNameView.setEnabled(False)
        self.lineNameView.setGeometry(QtCore.QRect(80, 30, 201, 20))
        self.lineNameView.setObjectName("lineNameView")
        self.lineSurname1View = QtWidgets.QLineEdit(self.centralwidget)
        self.lineSurname1View.setEnabled(False)
        self.lineSurname1View.setGeometry(QtCore.QRect(80, 60, 201, 20))
        self.lineSurname1View.setObjectName("lineSurname1View")
        self.lineSurname2View = QtWidgets.QLineEdit(self.centralwidget)
        self.lineSurname2View.setEnabled(False)
        self.lineSurname2View.setGeometry(QtCore.QRect(80, 90, 201, 20))
        self.lineSurname2View.setObjectName("lineSurname2View")
        self.lineDNIView = QtWidgets.QLineEdit(self.centralwidget)
        self.lineDNIView.setEnabled(False)
        self.lineDNIView.setGeometry(QtCore.QRect(80, 120, 201, 20))
        self.lineDNIView.setObjectName("lineDNIView")
        self.linePhoneView = QtWidgets.QLineEdit(self.centralwidget)
        self.linePhoneView.setEnabled(False)
        self.linePhoneView.setGeometry(QtCore.QRect(80, 150, 201, 20))
        self.linePhoneView.setObjectName("linePhoneView")
        self.ButtonEdit = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonEdit.setGeometry(QtCore.QRect(310, 60, 75, 23))
        self.ButtonEdit.setObjectName("ButtonEdit")
        self.ButtonSave = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonSave.setGeometry(QtCore.QRect(310, 90, 75, 23))
        self.ButtonSave.setObjectName("ButtonSave")
        self.ButtonExit = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonExit.setGeometry(QtCore.QRect(310, 120, 75, 23))
        self.ButtonExit.setObjectName("ButtonExit")
        self.listFlatView = QtWidgets.QListWidget(self.centralwidget)
        self.listFlatView.setGeometry(QtCore.QRect(20, 260, 401, 121))
        self.listFlatView.setObjectName("listFlatView")
        self.LabelFlatView = QtWidgets.QLabel(self.centralwidget)
        self.LabelFlatView.setGeometry(QtCore.QRect(160, 230, 91, 21))
        self.LabelFlatView.setObjectName("LabelFlatView")
        self.listFlatBook = QtWidgets.QListWidget(self.centralwidget)
        self.listFlatBook.setGeometry(QtCore.QRect(20, 420, 401, 121))
        self.listFlatBook.setObjectName("listFlatBook")
        self.LabelFlatBook = QtWidgets.QLabel(self.centralwidget)
        self.LabelFlatBook.setGeometry(QtCore.QRect(170, 390, 91, 21))
        self.LabelFlatBook.setObjectName("LabelFlatBook")
        self.listFlatBuy = QtWidgets.QListWidget(self.centralwidget)
        self.listFlatBuy.setGeometry(QtCore.QRect(20, 590, 401, 121))
        self.listFlatBuy.setObjectName("listFlatBuy")
        self.LabelFlatBuy = QtWidgets.QLabel(self.centralwidget)
        self.LabelFlatBuy.setGeometry(QtCore.QRect(170, 560, 91, 21))
        self.LabelFlatBuy.setObjectName("LabelFlatBuy")
        self.LabelEmail = QtWidgets.QLabel(self.centralwidget)
        self.LabelEmail.setGeometry(QtCore.QRect(20, 180, 61, 21))
        self.LabelEmail.setObjectName("LabelEmail")
        self.lineEmailView = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEmailView.setEnabled(False)
        self.lineEmailView.setGeometry(QtCore.QRect(80, 180, 201, 20))
        self.lineEmailView.setObjectName("lineEmailView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LabelName.setText(_translate("MainWindow", "Nombre:"))
        self.LabelSurname1.setText(_translate("MainWindow", "Apellido 1:"))
        self.LabelSurname2.setText(_translate("MainWindow", "Apellido 2:"))
        self.LabelDNI.setText(_translate("MainWindow", "DNI:"))
        self.LabelPhone.setText(_translate("MainWindow", "Teléfono:"))
        self.lineNameView.setText(_translate("MainWindow", "NameView"))
        self.lineSurname1View.setText(_translate("MainWindow", "Surname1View"))
        self.lineSurname2View.setText(_translate("MainWindow", "Surname2View"))
        self.lineDNIView.setText(_translate("MainWindow", "SurnameDNIView"))
        self.linePhoneView.setText(_translate("MainWindow", "PhoneView"))
        self.ButtonEdit.setText(_translate("MainWindow", "Editar"))
        self.ButtonSave.setText(_translate("MainWindow", "Guardar"))
        self.ButtonExit.setText(_translate("MainWindow", "Salir"))
        self.LabelFlatView.setText(_translate("MainWindow", "Lista de Favoritos"))
        self.LabelFlatBook.setText(_translate("MainWindow", "Lista de Reservas"))
        self.LabelFlatBuy.setText(_translate("MainWindow", "Lista de Compras"))
        self.LabelEmail.setText(_translate("MainWindow", "Email:"))
        self.lineEmailView.setText(_translate("MainWindow", "EmailView"))
        
        # Edit line widgets with data client
        self.lineNameView.setText(_translate("MainWindow", self.clientData['Name']))
        self.lineSurname1View.setText(_translate("MainWindow", self.clientData['Surname1']))
        self.lineSurname2View.setText(_translate("MainWindow", self.clientData['Surname2']))
        self.lineDNIView.setText(_translate("MainWindow", self.clientData['DNI']))
        self.linePhoneView.setText(_translate("MainWindow", self.clientData['Phone']))
        self.lineEmailView.setText(_translate("MainWindow", self.clientData['Email']))

        # mouse click connect functions
        self.ButtonEdit.clicked.connect(self.ClientViewEdit)
        self.ButtonSave.clicked.connect(self.ClientViewSave)
        self.ButtonExit.clicked.connect(self.ClientViewExit)

# methods related to the action buttons
        
    def ClientViewEdit(self):
        self.lineNameView.setEnabled(True)
        self.lineSurname1View.setEnabled(True)
        self.lineSurname2View.setEnabled(True)
        self.lineDNIView.setEnabled(True)
        self.linePhoneView.setEnabled(True)
        self.lineEmailView.setEnabled(True)

    def ClientViewSave(self):
        self.dbClientView.update({'Name': self.lineNameView.text()}, doc_ids = [self.clientData.doc_id])
        self.dbClientView.update({'Surname1': self.lineSurname1View.text()}, doc_ids = [self.clientData.doc_id])
        self.dbClientView.update({'Surname2': self.lineSurname2View.text()}, doc_ids = [self.clientData.doc_id])
        self.dbClientView.update({'DNI': self.lineDNIView.text()}, doc_ids = [self.clientData.doc_id])
        self.dbClientView.update({'Phone': self.linePhoneView.text()}, doc_ids = [self.clientData.doc_id])
        self.dbClientView.update({'Email': self.lineEmailView.text()}, doc_ids = [self.clientData.doc_id])
        print(self.dbClientView.all())

    def ClientViewExit(self):
        self.windowClientView.hide()
        